### ISSUE TITLE
Link to DIS

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepoll#7]
Edit: Priority :High
On the Main Menu Page, at the end of the current buttons, a new button 
"About WePoll"
Link offsite in new tab to:
https://www.dinnostudio.com/wepoll-deck

**Comment by adamosimpson21** [comment]
Challenge Level: 1

**Comment by adamosimpson21** [comment]
Migrate to React/Redux framework

Challenge Level: 8

**Comment by adamosimpson21** [comment]
Done, I'll push the changes later today
